### ISSUE TITLE
真机的时候，小程序后台后，五秒后触发断线重连

### ISSUE THREAD

**Issue by biubiupiu1** [weapp-socketio/weapp.socket.io#10]

**Comment by biubiupiu1** [comment]
你好，那有什么比较好的解决办法吗

**Comment by gongzili456** [comment]
@biubiupiu1 微信就是这么设计的，小程序不会被长时间驻留在的后台的。

**Comment by biubiupiu1** [comment]
好吧，可能要换ws来重写了。。。。

**Comment by gongzili456** [comment]
@biubiupiu1 这并不是你用什么重写就能解决的，这是微信就是这么设计的，就像iOS APP也不会一致在后台驻留一样，就算你写 Native 的 APP也不会一直在后台驻留的。希望你能理解。

**Comment by biubiupiu1** [comment]
好像是这样的，我试了下。。那就没解决办法了吗 @gongzili456

**Comment by gongzili456** [comment]
必然是没有。不过根本没有一直连接的必要呀。退出了程序为啥还要保持连接呢？

**Comment by biubiupiu1** [comment]
因为我弄得是一个多人在线小游戏，有邀请好友的过程，有时候等待好友进房间，可能放在后台等。然后再回到前台就断开连接了

**Comment by gongzili456** [comment]
那你应该在 Server 端写入房间状态，然后进入小程序时恢复连接与状态就可以了呀！

**Comment by biubiupiu1** [comment]
这个。。貌似我目前没想到该怎么写

**Comment by fanweixiao** [comment]
@biubiupiu1 使用微信的服务消息提醒来做吧。这个issue close掉了
