### ISSUE TITLE
服务端socket.io @4 能用这个包吗？

### ISSUE THREAD

**Issue by johnsmithsren** [weapp-socketio/weapp.socket.io#105]
**遇到了什么问题？**

**你的预期是什么？**

**截图:**

**项目版本号：**

**微信开发者工具**
 - 版本号：[e.g. 22]
 - 电脑 OS：[e.g. Windows 10]

**真机环境 (请完成填充下面的条码):**
 - OS 版本: [e.g. iOS8.1]
 - 微信版本 [e.g. 22]

**附加信息：**

**Comment by kingchen2008** [comment]
把代码下载下来，重新安装依赖包，我试过 用socket.io-client 4.1.3 包， 可以打包，可以使用。服务器端V4, 要求客户端版本最低是4.1.3.

**Comment by kingchen2008** [comment]
用socket.io-client 4.6.1打包，在微信小程序中使用，出现eval之类的错误。查看了socket.io-client源代码，没有发现有用eval之类的代码，可能没有找得更细。
TypeError: Cannot read property 'bind' of undefined
    at a (weapp.socket.io4.6.1.wx.js:1)
    at new q (weapp.socket.io4.6.1.wx.js:10)
    at V (weapp.socket.io4.6.1.wx.js:10)
    at Object.initSocketClient (initSocket.js:68)
    at eval (app.js? [sm]:301)
    at H (eval at n.call.document (runtime.js?devtools_ignore=true:1), <anonymous>:2:68639)
    at eval (eval at n.call.document (runtime.js?devtools_ignore=true:1), <anonymous>:2:68861)
    at C (eval at n.call.document (runtime.js?devtools_ignore=true:1), <anonymous>:2:38338)

**Comment by puzzle9** [comment]
> 

高于 `4.1.3` 的版本好像因为打包问题 直接用不了

**Comment by rayyzhong** [comment]
用4.1.3能动，不过webpack build的 `development` mode可用，用`production` mode 就出错。
![image](https://user-images.githubusercontent.com/6892732/233783625-09d1f384-cf55-4e3c-9fde-abc93b1ce311.png)

**Comment by rayyzhong** [comment]
@kingchen2008 老哥能不能贴一个可用版本的上来

**Comment by puzzle9** [comment]
[weapp.socket.io.wx-4.4.3.zip](https://github.com/weapp-socketio/weapp.socket.io/files/11301335/weapp.socket.io.wx-4.4.3.zip)

我记得打包的 prod 也行啊

**Comment by rayyzhong** [comment]
> [weapp.socket.io.wx-4.4.3.zip](https://github.com/weapp-socketio/weapp.socket.io/files/11301335/weapp.socket.io.wx-4.4.3.zip)
> 
> 我记得打包的 prod 也行啊

用你这个还是报一样的错，不过我找到了个方法，虽然大小会占用113KB。

https://github.com/rayyzhong/weapp.socket.io#using-with-socketio-v4-eg-v461

**Comment by puzzle9** [comment]
> > [weapp.socket.io.wx-4.4.3.zip](https://github.com/weapp-socketio/weapp.socket.io/files/11301335/weapp.socket.io.wx-4.4.3.zip)
> > 我记得打包的 prod 也行啊
> 
> 用你这个还是报一样的错，不过我找到了个方法，虽然大小会占用113KB。
> 
> https://github.com/rayyzhong/weapp.socket.io#using-with-socketio-v4-eg-v461

不会吧 我项目中用这个是正常的 没遇到这个错误
可以提供个能复现的demo吗

**Comment by kingchen2008** [comment]
> @kingchen2008 老哥能不能贴一个可用版本的上来
这个是用socket.io-client 4.1.3  打包生成的代码，可以使用。 其实就是把作者的代码下载下面，然后重新npm install依赖包，安装一下 socket.io-client 4.1.3 依赖包，再重新打包就生成这个我贴上来的js文件。

运行package.json文件里面的命令：
build:wechat

[weapp.socket.io.wx.zip](https://github.com/weapp-socketio/weapp.socket.io/files/11411664/weapp.socket.io.wx.zip)
