### ISSUE TITLE
远程调试的时候会一直发送 xhr 而无法切换到  websocket 协议

### ISSUE THREAD

**Issue by niices** [weapp-socketio/weapp.socket.io#11]
开发者工具本地测试没问题，远程调试的时候会一直发送 xhr 而无法切换到  websocket 协议
### 这是开发者工具的网络请求
![image](https://user-images.githubusercontent.com/8327775/42079823-53f114ec-7bb3-11e8-856e-7958054cf29b.png)
### 这是远程调试时的网络请求
![image](https://user-images.githubusercontent.com/8327775/42079908-9af0b88e-7bb3-11e8-8231-bd95014e417a.png)
### 写了一个小 demo，这是涉及到的代码
![image](https://user-images.githubusercontent.com/8327775/42079961-bc2584d0-7bb3-11e8-85d1-5be1a3531a45.png)
### 这是在 socket.io 执行`io('your server address')`得到的结果
![image](https://user-images.githubusercontent.com/8327775/42080075-05f155b2-7bb4-11e8-854e-6e6a9f0d8ae3.png)

**Comment by gongzili456** [comment]
升级到最新版本了？

**Comment by niices** [comment]
开发者工具跟`weapp.socket.io.js`都是最新版本
基础库测试了用户量比较多的库都是这个结果

**Comment by gongzili456** [comment]
最新的版本是去掉了 xhr 的方式了的。我远程调试测试过没有问题，也没有找到如何在远程调试时查看网络请求。

**Comment by niices** [comment]
[socket.io.demo.zip](https://github.com/weapp-socketio/weapp.socket.io/files/2148359/socket.io.demo.zip)
您看一下我发的这个demo
![image](https://user-images.githubusercontent.com/8327775/42080704-1f0ed46e-7bb6-11e8-9bca-8d483937c441.png)
然后远程调试的时候切换到 NetWork 可以看到还是发送的 xhr 请求

**Comment by gongzili456** [comment]
应该是开发者工具的问题，远程调试时确实 xhr 方式没有切换成功，但是手机上确实连接成功了，进行消息通讯都是没有问题的。你可以添加一些事件通讯检查一下。

**Comment by niices** [comment]
谢谢 确实是开发者工具的问题

**Comment by niices** [comment]
谢谢您  确实是开发者工具的问题
