### ISSUE TITLE
合作伙伴征集中

### ISSUE THREAD

**Issue by gongzili456** [weapp-socketio/weapp.socket.io#13]
如果你的项目正在使用 [weapp.socket.io](https://github.com/weapp-socketio/weapp.socket.io) 欢迎留下你的项目信息（名称，Logo，小程序二维码，官网等），我会将信息放在 weapp.socket.io 的 [官方首页](http://weappsocket.matong.io/) 上展出。欢迎在下面提交您的项目。

**Comment by h357650113** [comment]
词汇玩家小程序，沪江，正在测试使用 weapp.socket.io

**Comment by gongzili456** [comment]
@h357650113 可以留下 小程序二维码，或者logo之类的信息吗？

**Comment by h357650113** [comment]
我想问下，支不支持 ws ? 连接直接换成 ws 不可用

**Comment by h357650113** [comment]
@gongzili456 微信小程序 - 词汇玩家

**Comment by gongzili456** [comment]
@h357650113 连接可以直接写成 ws 的，但是推荐使用 wss

**Comment by h357650113** [comment]
ws 第一次使用会有两条 http 请求一同产生，之后 disconnect，再次 open 就会变成 http，可能是什么原因引起的？

**Comment by beiluo0** [comment]
我加了一个namespace，就一直连接不上，怎么回事呢？

**Comment by SCParrot** [comment]
我再原生版上无法添加header，请问是怎么回事呢？
    const socket = (this.socket = io(
      'https://socket-io-chat.now.sh/', {
        transportOptions: {
          polling: {
            extraHeaders: {
              'instant-auth-schema': 'DOCTOR',
              'instant-care-auth-token': 'tVgmK5EbYK3P7GVg8HfCqlnBNg2rA6WL',
              'instant-care-auth-id': 4,
            }
          }
        }
      }
    ))
