### ISSUE TITLE
服务端或客户端任意一端断开连接就报错

### ISSUE THREAD

**Issue by 13078417792** [weapp-socketio/weapp.socket.io#53]
开发框架是Taro+TS
服务端断开连接或客户端主动断开连接时就会报错。
![image](https://user-images.githubusercontent.com/22026159/78470200-1e757e80-775a-11ea-9a00-b5064eb454e3.png)

主要的代码
```
// WebSocket.ts
import SocketIO, { WeappSocketInstance } from 'weapp.socket.io'


export class WebSocket {

    private _ws: WeappSocketInstance;

    private _url: string

    constructor(url: string){
        this._url = url
        const ws = SocketIO(url)
        
    }
} 


export default new WebSocket("ws://127.0.0.1:7200")

// app.tsx
// ...
import ws from '../utils/WebSocket'
console.log(ws)
```

`WeappSocketInstance`是我自己在TS声明的类型

**Comment by 13078417792** [comment]
貌似是这里报错了
![image](https://user-images.githubusercontent.com/22026159/78472012-30f6b480-7768-11ea-8588-017aa1041fbc.png)

![image](https://user-images.githubusercontent.com/22026159/78472308-3bb24900-776a-11ea-9be1-cdf5cf7363ca.png)
`this._socket.close`貌似是调用了微信的`ws.closeSocket`，但是这个API应该没有返回值吧。

**Comment by gongzili456** [comment]
是一个拼写错误，已经修正，感谢提醒。
