### ISSUE TITLE
socket.close() 关闭时候 会有报错，是库的问题

### ISSUE THREAD

**Issue by MonsterRHD** [weapp-socketio/weapp.socket.io#55]
![image](https://user-images.githubusercontent.com/22114576/79815419-49471000-83b3-11ea-96e7-64e092e09da0.png)
thirdScriptError
setTimeout expects a function as first argument but got undefined.;at pages/chat/index onUnload function;at setTimeout callback function
TypeError: setTimeout expects a function as first argument but got undefined.

**Comment by MonsterRHD** [comment]
好像之前有个版本 是不会报错的




[weapp.socket.io的副本.docx](https://github.com/weapp-socketio/weapp.socket.io/files/4507403/weapp.socket.io.docx)

**Comment by SunGg12138** [comment]
这个问题我也遇到了，白思不得其解

**Comment by MonsterRHD** [comment]
> 这个问题我也遇到了，白思不得其解

就我那个第二条留言 上传的 是没有的  就是120kb而已 多了20kb

**Comment by SunGg12138** [comment]
解决了 谢了

**Comment by MonsterRHD** [comment]
我下载下来 好像打不开哦·····

**Comment by SunGg12138** [comment]
把后缀名称改成.js就好

**Comment by sillysilly** [comment]
把上面的副本下载了替换了index.js还是报错是为什么?有没有解决办法呢谢谢

**Comment by sillysilly** [comment]
Cannot read property 'close' of undefined

**Comment by gongzili456** [comment]
> ![image](https://user-images.githubusercontent.com/22114576/79815419-49471000-83b3-11ea-96e7-64e092e09da0.png)
> thirdScriptError
> setTimeout expects a function as first argument but got undefined.;at pages/chat/index onUnload function;at setTimeout callback function
> TypeError: setTimeout expects a function as first argument but got undefined.

感谢反馈，问题已经修复。

**Comment by MonsterRHD** [comment]
刚才试了下 还是有报错呢

liuguili <notifications@github.com>于2020年4月27日 周一22:29写道：
