### ISSUE TITLE
小程序引入使用后不生效，connect不上了。在小程序开发者工具中可以，真机不可以，有人遇到这个问题吗？

### ISSUE THREAD

**Issue by liangshanshan** [weapp-socketio/weapp.socket.io#56]
2019年的时候还能用，还能connect成功，收发信息。但最近上去看，发现代码还是原来的代码，却connect不上了。安卓手机是直接没有反应，ios是报closeSocket:fail wcwss taskID not exist错误。后台看到并没有连接上。

**Comment by gongzili456** [comment]
请问使用的是最新版本吗？

**Comment by liangshanshan** [comment]
> 请问使用的是最新版本吗？

是的，是最新版。麻烦帮我看看这个问题。谢谢啦

**Comment by gongzili456** [comment]
麻烦你多提供一些信息，代码片段或者截图啥的

**Comment by liangshanshan** [comment]
首页用到的主要代码如下： 
console.log("我是有全局变量",app.globalData.connect_socket)
        if (app.globalData.socket) {
            console.log("我是有socket的")
            // app.globalData.socket.disconnect()
            app.globalData.socket = ""
            app.globalData.connect_socket = 0;
            
        }
        app.globalData.socket = io(util.baseSocket)
        console.log('我是赋值',app.globalData.socket)
        app.globalData.socket.on('connect', () => {
            console.log('我是connect这里', app.globalData.socket)
            if (wx.getStorageSync("playerId")){
               //发送登录信息
                app.globalData.socket.emit('login', 'wx2e1383baxxxxaxxx', wx.getStorageSync("playerId"));
                app.globalData.connect_socket = 1;
            }
        });
        app.globalData.socket.on('new_msg', res => {
            console.log('received news: ', res);
            let res_deal = JSON.parse(res);
            console.log(res_deal);
            console.log(res_deal.cabinet_id + '柜' );
            console.log(app.globalData.end_grid)
            util.popTip('结单提醒', '您使用的' + res_deal.cabinet_id + '柜' + '已自动为您结单，感谢您的使用！', '知道啦', false, () => {
                wx.navigateBack({ delta: 1 })
            }, () => { })
        })
真机调试的时候是安卓是直接没有进入打印connect的。无论是不是第一次。ios的话就是报closeSocket:fail wcwss taskID not exist错误，而且是一直都在报这个错。清除缓存，删了小程序再次进来也是会报这个错。我用的是提问的时候用的最新版。你前天更新的版本我一引入安卓就报错啦。麻烦帮忙看看。

**Comment by gongzili456** [comment]
> 首页用到的主要代码如下：
> console.log("我是有全局变量",app.globalData.connect_socket)
> if (app.globalData.socket) {
> console.log("我是有socket的")
> // app.globalData.socket.disconnect()
> app.globalData.socket = ""
> app.globalData.connect_socket = 0;
> 
> ```
>     }
>     app.globalData.socket = io(util.baseSocket)
>     console.log('我是赋值',app.globalData.socket)
>     app.globalData.socket.on('connect', () => {
>         console.log('我是connect这里', app.globalData.socket)
>         if (wx.getStorageSync("playerId")){
>            //发送登录信息
>             app.globalData.socket.emit('login', 'wx2e1383baxxxxaxxx', wx.getStorageSync("playerId"));
>             app.globalData.connect_socket = 1;
>         }
>     });
>     app.globalData.socket.on('new_msg', res => {
>         console.log('received news: ', res);
>         let res_deal = JSON.parse(res);
>         console.log(res_deal);
>         console.log(res_deal.cabinet_id + '柜' );
>         console.log(app.globalData.end_grid)
>         util.popTip('结单提醒', '您使用的' + res_deal.cabinet_id + '柜' + '已自动为您结单，感谢您的使用！', '知道啦', false, () => {
>             wx.navigateBack({ delta: 1 })
>         }, () => { })
>     })
> ```
> 
> 真机调试的时候是安卓是直接没有进入打印connect的。无论是不是第一次。ios的话就是报closeSocket:fail wcwss taskID not exist错误，而且是一直都在报这个错。清除缓存，删了小程序再次进来也是会报这个错。我用的是提问的时候用的最新版。你前天更新的版本我一引入安卓就报错啦。麻烦帮忙看看。

你上面这段代码是写在了 app.js 文件里面还是写在了 page 里面？根据你的描述说 iOS 报错 taskID 不存在，原因应该是在 closeSocket 的时候没有成功创建 connection，请展示更多的使用细节方便定位

**Comment by liangshanshan** [comment]
是写在首页的index.js里面的并且是放在onload里面。我用的地方就是这个位置而已呢，还有就是在utils.js里面写的请求封装里面接口超时的时候有再次调用app.globalData.socket.emit('login', 'wx2e1383baxxxxaxxx', wx.getStorageSync("playerId"));重新发送用户重新登录而已。就这两个位置，没有其他位置了。connect的话就只在index.js里面有

**Comment by gongzili456** [comment]
建议参考我写的 Demo 项目 https://github.com/weapp-socketio/socket.io-weapp-demo

**Comment by liangshanshan** [comment]
> 建议参考我写的演示项目https://github.com/weapp-socketio/socket.io-weapp-demo

你好，我看了一下午你的代码。然后在本地剩你的引用的weapp.socket.io.js，单运行你的项目是可以的，排除了很久，发现是url的问题 。你连接的地址是
        const socket = (this.socket = io( 'https://socketio-chat-h9jt.herokuapp.com/' ))
但是我们按照官方的地址是const socket = (this.socket = io("wss://dev.xxx.club:2120"))
按你的url连接是能成功丢我项目也能成功，但是一换微信这个官网的url就报错了，connect不上。然后就出现WebSocket was closed before the connection was established，出现这个问题是因为connect不上吧。麻烦再帮我看看

**Comment by liangshanshan** [comment]
> 建议参考我写的演示项目https://github.com/weapp-socketio/socket.io-weapp-demo

你好，我看了一下午你的代码。然后在本地删除你项目多余文件只剩余你引用的weapp.socket.io.js，单运行你的项目是可以的，排除了很久，发现是url的问题。你连接的地址是
const socket =（this.socket = io（' https://socketio-chat-h9jt.herokuapp.com/ '））
但是我们按照官方的地址是const socket =（this.socket = io（“ wss： //dev.xxx.club:2120“））
按你的url连接是能成功丢我项目也能成功，但是一换微信这个官网的url就报错了，connect不上。然后就出现WebSocket在关闭之前连接已建立，出现这个问题是因为connect不上吧。麻烦再帮我看看

**Comment by gongzili456** [comment]
URL使用 `wss` 协议同样是可以创建连接的，加端口号也是可以的。还是请确认你的服务器是否有正确的 socket.io 服务吧

**Comment by liangshanshan** [comment]
好的，谢谢哈
