### ISSUE TITLE
关闭 socket的时候 还是有报错。

### ISSUE THREAD

**Issue by MonsterRHD** [weapp-socketio/weapp.socket.io#57]
![image](https://user-images.githubusercontent.com/22114576/80448541-30a89e00-894f-11ea-8d8e-db189ffcb814.png)

**Comment by MonsterRHD** [comment]
最新的也还是这样的 微信小程序

**Comment by gongzili456** [comment]
请问你clone的代码，最新的commit是 [3d3aa47](https://github.com/weapp-socketio/weapp.socket.io/commit/3d3aa47094968493ebbe7ff46287f42bd39ea23d) 吗？

**Comment by MonsterRHD** [comment]
> 请问你clone的代码，最新的commit是[3d3aa47](https://github.com/weapp-socketio/weapp.socket.io/commit/3d3aa47094968493ebbe7ff46287f42bd39ea23d)吗？
是的，是最新的 头疼，那个之前 120多KB 有点大，，现在新的88kb 感觉还可以 就是还是有报错的

**Comment by gongzili456** [comment]
可以贴一下代码片段吗？建议参考我写的 Demo 小程序 https://github.com/weapp-socketio/socket.io-weapp-demo
可以在这个项目里面调试你的代码

**Comment by MonsterRHD** [comment]
> 可以贴一下代码片段吗？建议参考我写的 Demo 小程序 https://github.com/weapp-socketio/socket.io-weapp-demo
> 可以在这个项目里面调试你的代码

https://developers.weixin.qq.com/s/LZVUpXmh7ugu
好了 就是需要重新替换下里面的wssURL

**Comment by gongzili456** [comment]
我看了你分享的code，里面引用的类库版本是之前的，替换成最新版本即可。

**Comment by MonsterRHD** [comment]
> 我看了你分享的code，里面引用的类库版本是之前的，替换成最新版本即可。

![image](https://user-images.githubusercontent.com/22114576/80558413-e2f26b00-8a0c-11ea-8e02-081c26e98a11.png)
 我从这里下载下来 用的lib里的呀

**Comment by gongzili456** [comment]
明白了，我不应该把 lib 放在那，我会删掉这个目录以免发生歧义，如果通过源码来使用，建议还是自己 build。

**Comment by MonsterRHD** [comment]
> 明白了，我不应该把 lib 放在那，我会删掉这个目录以免发生歧义，如果通过源码来使用，建议还是自己 build。

辛苦了
