### ISSUE TITLE
在mpx框架中无法发起连接，也不报错，但是同样的写法在原生小程序下却是好的

### ISSUE THREAD

**Issue by leowang1028** [weapp-socketio/weapp.socket.io#59]

**Comment by AnsonKong** [comment]
我在 taro 框架中遇到同样的问题：
```
const socket = (this.socket = io(
  'https://socketio-chat-h9jt.herokuapp.com/'
));
console.log('socket: ', socket);
socket.on('connect', () => {
  console.log("connect");
});
```
不会出现 'connect' 的 log，使用 weapp.socket.io.dev.js 的话会发现在不断重试。

**Comment by AnsonKong** [comment]
解决方法：引用 weapp.socket.io.dev.js，并在 3650 行，把 NodeWebSocket 的赋值语句抽取出来就好，因为默认原生小程序中 window 是 undefined，但是 Taro 框架会自动填充 window 对象，导致 weapp.socket.io 判断错误。 @leowang1028 会不会 mpx 框架也是这原因，可以试试。

**Comment by zfha** [comment]
> 解决方法：引用 weapp.socket.io.dev.js，并在 3650 行，把 NodeWebSocket 的赋值语句抽取出来就好，因为默认原生小程序中 window 是 undefined，但是 Taro 框架会自动填充 window 对象，导致 weapp.socket.io 判断错误。 @leowang1028 会不会 mpx 框架也是这原因，可以试试。

抽取出来是什么意思呢？

**Comment by Jane0220** [comment]
> 
> 
> 解决方法：引用 weapp.socket.io.dev.js，并在 3650 行，把 NodeWebSocket 的赋值语句抽取出来就好，因为默认原生小程序中 window 是 undefined，但是 Taro 框架会自动填充 window 对象，导致 weapp.socket.io 判断错误。 @leowang1028 会不会 mpx 框架也是这原因，可以试试。

@AnsonKong 同样在Taro3.0碰到了，3650行的处理没有太明白，试了没有成功，可以仔细说明一下怎么处理吗？

**Comment by Jane0220** [comment]
> 
> 
> > 解决方法：引用 weapp.socket.io.dev.js，并在 3650 行，把 NodeWebSocket 的赋值语句抽取出来就好，因为默认原生小程序中 window 是 undefined，但是 Taro 框架会自动填充 window 对象，导致 weapp.socket.io 判断错误。 @leowang1028 会不会 mpx 框架也是这原因，可以试试。
> 
> 抽取出来是什么意思呢？

@zfha 我会了，在Taro3.0按照大佬的方法解决完，在weapp.socket.io.dev.js，并在 3650 行附近有
`
var WebSocketImpl = BrowserWebSocket || NodeWebSocket;
`
在这个上方有判断

`
if (typeof window === 'undefined') {
  try {
    NodeWebSocket = __webpack_require__(/*! ws */ "./src/wx-ws.js");
  } catch (e) { }
}
`
把if和try catch的判断全部去掉，只保留中间的NodeWebSocket的赋值（微信小程序走的是NodeWebSocket，且没有window（但Taro3.0好像这里判断会有问题，就像上面说的））

如果想用weapp.socket.io.js版本，搜索到MozWebSocket关键字，后面的if的判断以及try catch去掉，把中间的赋值抽出来即可

**Comment by gongzili456** [comment]
@zfha @Jane0220 @AnsonKong @leowang1028  新版本已经解决
