### ISSUE TITLE
Kbone框架无反应

### ISSUE THREAD

**Issue by zfha** [weapp-socketio/weapp.socket.io#62]
**遇到了什么问题？**
kbone 框架下面执行以后，没有反应，io(XXX) 有返回值，但是不会触发 connect 监听，
也不会触发 error，timeout等等

**Comment by feiren200** [comment]
可以看下我刚发的 issue
https://github.com/weapp-socketio/weapp.socket.io/issues/63

**Comment by gongzili456** [comment]
@zfha 新版本已经解决该问题
