### ISSUE TITLE
小程序接入无反应问题反馈

### ISSUE THREAD

**Issue by feiren200** [weapp-socketio/weapp.socket.io#63]
1. 克隆项目到本地
2. 安装依赖
3. 运行 npm run build-dev
问题就出来图中红框内
![image](https://user-images.githubusercontent.com/28645656/96206358-4e200180-0f9b-11eb-9d14-84f5a34210c5.png)
说下思路：看源码不难发现作者是使用自己封装的小程序socket来替换socket.io-client中的socket。
![image](https://user-images.githubusercontent.com/28645656/96207756-8ffe7700-0f9e-11eb-81e6-e7e06acd1dd0.png)
socket.io-client支持在浏览器环境和node环境使用，而socket.io-client就是使用第一张图中的逻辑来判断使用环境。
作者就是利用小程序也没有window的特点，将node环境的socket替换成自己封装的小程序socket。目的就是让socket.io-client拿到一个可用的socket。
而新的小程序有window使得socket.io-client拿不到可用的socket，也就导致了小程序引入插件却没有建立socket链接也不报错。
ps: socket.io-client 在没有拿到undefined应该要报错的呀

**Comment by gongzili456** [comment]
@feiren200 感谢反馈，会及时更新

**Comment by gongzili456** [comment]
@feiren200 该问题已解决，可以安装新版本 `weapp.socket.io@2.1.0` 或 clone 新代码自行编译使用
