### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by deqwin** [weapp-socketio/weapp.socket.io#64]
**遇到了什么问题？**
node端引入但未使用时，报错：ReferenceError: window is not defined
https://github.com/urain39/stuff/issues/33

**你的预期是什么？**

**截图:**

**项目版本号：**

**微信开发者工具**
 - 版本号：[e.g. 22]
 - 电脑 OS：[e.g. Windows 10]

**真机环境 (请完成填充下面的条码):**
 - OS 版本: [e.g. iOS8.1]
 - 微信版本 [e.g. 22]

**附加信息：**

**Comment by gongzili456** [comment]
本项目是使用在小程序环境中的，无法在Server端使用
