### ISSUE TITLE
websocket was closed before the connection was established

### ISSUE THREAD

**Issue by fangxu864** [weapp-socketio/weapp.socket.io#66]
微信小程序，ios系统，经常报 “websocket was closed before the connection was established” 是什么原因？请问大佬如何解决

**Comment by 334249477** [comment]
同问

**Comment by zhengmenghuang** [comment]
同问

**Comment by Cople** [comment]
我这也是一直报这个错，iOS 14.4.2 微信 8.0.2

**Comment by lzfxxx** [comment]
请问有人找到解决方法了吗

**Comment by gongzili456** [comment]
> 请问有人找到解决方法了吗

请确认 Server 和 Client 的 socket.io 版本是否对应
