### ISSUE TITLE
可能是bug

### ISSUE THREAD

**Issue by meixuexiang** [weapp-socketio/weapp.socket.io#8]
WS.prototype.doOpen:
`    success: function(res) {
      debug('websocket-weapp connected success.', res)
      this.socketTaskId = res.socketTaskId
    },`

在微信开发者工具里：
`o = e.apply(e, arguments);`

success回调里的this就变成了匿名函数本身，设置socketTaskId没有意义，导致doClose也没有意义了

**Comment by gongzili456** [comment]
已修复
