### ISSUE TITLE
目前是不是不支持polling模式？

### ISSUE THREAD

**Issue by airqj** [weapp-socketio/weapp.socket.io#83]
感谢大神的工作。
目前使用polling模式的时候发现无法连接服务器，查了一下发现其他人也有这问题     
然而官方文档写的是支持websocket,polling模式，如果文档写错了改一下吧 :)

**Comment by gongzili456** [comment]
是的，小程序本身仅支持 websocket 模式，所以本项目剔除了 polling 模式。

**Comment by airqj** [comment]
> 是的，小程序本身仅支持 websocket 模式，所以本项目剔除了 polling 模式。

了解了  感谢回复    
官网有空可以更正一下  :)
