### ISSUE TITLE
想请教这个包的目的到底什么？

### ISSUE THREAD

**Issue by qiulang** [weapp-socketio/weapp.socket.io#88]
你好，我想请教一下这个包的目的到底什么？

我觉得我对socket.io 还算比较熟悉，但是我最近刚刚知道咱们这个包。我大致浏览了一下代码，但是一时没看出这个包到底是要解决什么问题(我没做过小程序开发)。

开始我以为是为了去掉一些对小程序没用东西（比如去掉 polling），让打包出来的代码更小。但是我试着打包下，发现打包出来的代码比 socket.io-client[自己打包的代码](https://github.com/socketio/socket.io-client/tree/main/dist)还大，所以我有点糊涂了。

**Comment by gongzili456** [comment]
这个项目是针对小程序环境打包的 socket.io client

**Comment by waynerQiu** [comment]
项目不错，我用到了
不过最近另一个项目需要用到1.4.8的socket.io-client，发现咱们的项目是基于3.0开发的，
请教一下能否基于1.4.8搞一个呢？

**Comment by gongzili456** [comment]
最早是基于 2.0.3 做的，你可以使用项目的第一个 commit 来编译一下试试看能否兼容你的 1.4.8
