### ISSUE TITLE
请问支持支付宝小程序吗？

### ISSUE THREAD

**Issue by parkyang** [weapp-socketio/weapp.socket.io#95]
======package.json:
"dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.5.7",
    "@tarojs/helper": "3.5.7",
    "@tarojs/plugin-framework-react": "3.5.7",
    "@tarojs/plugin-platform-alipay": "3.5.7",
    "@tarojs/plugin-platform-jd": "3.5.7",
    "@tarojs/plugin-platform-qq": "3.5.7",
    "@tarojs/plugin-platform-swan": "3.5.7",
    "@tarojs/plugin-platform-tt": "3.5.7",
    "@tarojs/plugin-platform-weapp": "3.5.7",
    "@tarojs/react": "3.5.7",
    "@tarojs/router": "3.5.7",
    "@tarojs/runtime": "3.5.7",
    "@tarojs/shared": "3.5.7",
    "@tarojs/taro": "3.5.7",
    "@tarojs/taro-h5": "3.5.7",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "socket.io-client": "^4.5.3",
    "weapp.socket.io": "^3.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
    "@tarojs/cli": "3.5.7",
    "@tarojs/webpack5-runner": "3.5.7",
    "@types/react": "^18.0.0",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "babel-preset-taro": "3.5.7",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.5.7",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "react-refresh": "^0.11.0",
    "stylelint": "^14.4.0",
    "typescript": "^4.1.0",
    "webpack": "5.69.0"
  }

===============code:
const socket = io('wss://xxx.com'); // 代码执行没反应，不发请求

**Comment by gongzili456** [comment]
目前还不支持，欢迎 PR

**Comment by parkyang** [comment]
请问支付宝小程序有类似解决方案吗？网上一直没找到！希望能指点一下小弟！谢谢

**Comment by gongzili456** [comment]
@parkyang 现在已经支持了 支付宝小程序
可以手动执行不同平台的 build 命令

```
    "build-dev:alipay": "webpack --config webpack.config.dev.js --env.target=Alipay",
    "build-dev:wechat": "webpack --config webpack.config.dev.js --env.target=Wechat",
    "build:alipay": "webpack --config webpack.config.js --env.target=Alipay",
    "build:wechat": "webpack --config webpack.config.js --env.target=Wechat",
```

**Comment by parkyang** [comment]
非常感谢！我改了一版别人的代码【hyoga-uni-socket.io(1.0.0)】，也支持了支付宝小程序了^_^！
